services:
  postgres:
    build: ./db
    # image: postgres:18
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: online
      POSTGRES_USER: online
      POSTGRES_PASSWORD: online
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    command: |
      postgres
      -c shared_preload_libraries=pg_stat_statements,pg_cron
      -c wal_level=replica
      -c hot_standby=on
      -c shared_buffers=512MB
      -c maintenance_work_mem=128MB
      -c effective_io_concurrency=2
      -c min_wal_size=1GB
      -c max_wal_size=3GB
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"
    #       memory: 256M

  redis:
    image: docker.io/bitnami/redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: online
    volumes:
      - redis:/bitnami
    ports:
      - "6379:6379"

  aspire-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    restart: unless-stopped
    ports:
      - 18888:18888
      - 18889:18889

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "18080:8080"
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: online
      KC_DB_PASSWORD: online
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: http://localhost:18080
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - ./other/keycloakThemes:/opt/keycloak/providers/

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
  redis:
  mailpit:
