services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: online
      POSTGRES_USER: online
      POSTGRES_PASSWORD: online
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: |
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c wal_level=replica
      -c hot_standby=on
      -c shared_buffers=512MB
      -c maintenance_work_mem=128MB
      -c effective_io_concurrency=2
      -c min_wal_size=1GB
      -c max_wal_size=3GB
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.2"
    #       memory: 256M

  redis:
    image: docker.io/bitnami/redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: online
    ports:
      - "6379:6379"

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
      - 18889:18889

volumes:
  pgdata:
